# Generated by Django 3.0.6 on 2020-08-07 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('name', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('status', models.BooleanField(default=0)),
                ('description', models.TextField(max_length=400)),
                ('quotes', models.BooleanField(blank=True, default=0)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True)),
                ('slug', models.CharField(max_length=60, unique=True)),
                ('status', models.BooleanField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(max_length=400)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('main_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.MainMenu')),
            ],
        ),
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('description', models.TextField(max_length=400)),
                ('joindate', models.CharField(max_length=60)),
                ('main_menu', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='menu.MainMenu')),
            ],
        ),
    ]
