# Generated by Django 3.0.6 on 2020-08-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='image',
            field=models.ImageField(blank=True, upload_to='news'),
        ),
    ]
