# Generated by Django 3.0.6 on 2020-08-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuitems_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='price',
            field=models.CharField(default='3', max_length=100),
        ),
    ]
