# Generated by Django 3.0.6 on 2020-08-07 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menuitems_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainmenu',
            name='quotes',
        ),
    ]
