# Generated by Django 3.0.6 on 2020-08-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_remove_mainmenu_quotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitems',
            name='image',
            field=models.ImageField(blank=True, upload_to='pictures'),
        ),
    ]
