# Generated by Django 3.0.6 on 2020-08-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20200807_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmenu',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
